import { chromium } from '/opt/node22/lib/node_modules/playwright/index.mjs';
const browser = await chromium.launch();
const ctx = await browser.newContext({ viewport: { width: 390, height: 780 } });
const p = await ctx.newPage();
const errors = [];
p.on('pageerror', e => errors.push(e.message));
await p.goto('http://127.0.0.1:8741/index.html', { waitUntil: 'domcontentloaded' });
await p.waitForSelector('input[type=text]');
const m5 = await p.locator('div:text-is("-5")').count();
console.log('-5 preset:', m5 === 1 ? 'OK' : 'FAIL');
await p.locator('div:text-is("-5")').click();
const active = await p.locator('div:text-is("-5")').evaluate(el => el.style.background);
console.log('-5 selectable:', active.includes('43')||active.includes('var(--acc)') ? 'OK highlighted' : 'FAIL ' + active);
// plan with -5 → buffer chip shows -5 min buffer
await p.locator('text=Ankomst kl.').click();
const inputs = p.locator('input[type=text]');
await inputs.nth(0).fill('Bergen');
await p.locator('text=Bergen, Vestland').first().click();
await inputs.nth(1).fill('Ålesund');
await p.locator('text=Ålesund, Møre og Romsdal').first().click();
await p.locator('text=Finn rute').click();
await p.waitForSelector('text=Avreise senest', { timeout: 10000 });
const chip = await p.locator('text=-5 min buffer').count();
console.log('planned with -5 buffer:', chip >= 1 ? 'OK' : 'FAIL');
await ctx.close(); await browser.close();
console.log(errors.length ? 'PAGE ERRORS:\n' + errors.join('\n') : 'no page errors');
